### ISSUE TITLE
Rewind 

### ISSUE THREAD

**Issue by muezis** [foosiee/Spotify-Lyrics-v2-public#3]
This is perfect. But one thing is missing - rewind by clicking on the playback bar (as it works in all players). Please add it. I learn the language by reading the lyrics, and it is important for me to be able to rewind and pause to listen a particular phrase again.

And maybe it would be better if the text was in the middle of the screen

**Comment by foosiee** [comment]
Hi, thanks for the suggestion! I'll get working on this. Have been meaning to update the player for sometime.

**Comment by muezis** [comment]
> Hi, thanks for the suggestion! I'll get working on this. Have been meaning to update the player for sometime.

And please make the playback strip as long. As it is on Spotify. Cause some make it short, and it impossible to rewind for a few seconds. I hope you understand what I mean)

**Comment by foosiee** [comment]
Closed by 5aa8848dc720e4929caf41849b3bbf07b9fb7c4c
