### ISSUE TITLE
Text on the center of the screen

### ISSUE THREAD

**Issue by muezis** [foosiee/Spotify-Lyrics-v2-public#4]
Hey. Thank you for implementing rewinding. Although it might been better to do a playback strip, but thank you anyway.

I have another idea. Perhaps it would be better if the text was in the center of the screen. It doesn't look good on my ultrawide monitor. https://imgur.com/a/w7srYGJ

**Comment by foosiee** [comment]
Wont be putting text in the center, I'm planning on doing other things with the right side of the screen eventually. May do a playback strip in the future.
